services:
  optimiser:
    build:
      args:
        SERVICE_NAME: "optimiser"
      context: .
    command: "dist/src/index.js"
    environment:
      PREDICTIONS_API: "http://predictions:3000"
      BATTERY_API: "http://battery:4000"
      MARKET_API: "http://market:5000"
    depends_on:
      - battery
      - predictions
      - market

  battery:
    build:
      args:
        SERVICE_NAME: "battery"
      context: .
    command: "dist/src/server.js"

  predictions:
    build:
      args:
        SERVICE_NAME: "predictions"
      context: .
    command: "dist/src/server.js"

  market:
    build:
      args:
        SERVICE_NAME: "market"
      context: .
    command: "dist/src/server.js"
